### ISSUE TITLE
Hello, may I have not started to officially execute the code during training, and an error was reported after downloading inception-2015-12-05.tgz ininceptionscore.py 

### ISSUE THREAD

**Issue by fxlong** [vt-vl-lab/Guided-pix2pix#9]
ValueError: Tensor._shape cannot be assigned, use Tensor.set_shape instead. I also reported an error after using Tesnor.set_shaoe instead of Tensor._shape because the shape is empty

**Comment by kmaeii** [comment]
> ValueError: Tensor._shape cannot be assigned, use Tensor.set_shape instead. I also reported an error after using Tesnor.set_shaoe instead of Tensor._shape because the shape is empty

Hi,
The task you running is 'Pose'? Did you have unzip the Deepfashion dataset ? How much MB are the unzipped file? I got a 3.4T file, but it is too large for my server. Do you have any way to solve this question?
Best regards

**Comment by BadourAlBahar** [comment]
Not sure why you get this. Would you please provide more details to what you are running. For example, what is the task, input/output, base model used (Unet/Resnet)? Also, which line is causing this?
Also, if this is being caused by "inceptionscore.py", feel free to remove this and then compute the inception score using another approach (if needed).
